# Generated by Django 5.2.17 on 2026-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ManyToManyField(to='agenda.categoria'),
        ),
    ]
