# Generated by Django 5.2.17 on 2026-09-02 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_evento_created_at_evento_ubicacion_evento_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(max_length=20)),
                ('quantidade_lembretes', models.PositiveIntegerField(default=0)),
                ('ultimo_lembrete', models.DateTimeField(blank=True, null=True)),
                ('ultima_interacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='agenda.evento')),
            ],
            options={
                'unique_together': {('evento', 'numero_whatsapp')},
            },
        ),
    ]
