# Generated by Django 5.2.17 on 2026-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='role',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('PREMIUM', 'Premium'), ('ADMIN', 'Admin')], default='USUARIO', max_length=20),
        ),
    ]
