# Generated by Django 4.2.11 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0002_livesession_liveparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='average_time_per_question',
            field=models.FloatField(default=0, help_text='Tiempo promedio por pregunta en segundos'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='question_times',
            field=models.JSONField(default=dict, help_text='Tiempo por pregunta en segundos'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]