# Generated by Django 4.2.11 on 2026-09-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz_app', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('badge_icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('achievement_type', models.CharField(choices=[('SKILL_MASTERY', 'Skill Mastery'), ('STREAK', 'Learning Streak'), ('SPEED_RUN', 'Speed Run'), ('PERFECT_SCORE', 'Perfect Score'), ('HELPING_OTHERS', 'Helping Others'), ('DISCOVERY', 'Discovery'), ('COMPLETION', 'Path Completion')], max_length=50)),
                ('points_reward', models.IntegerField(default=50)),
                ('criteria', models.JSONField(default=dict)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['rarity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('setup_code', models.TextField(help_text='Código de setup do ambiente')),
                ('solution_code', models.TextField(help_text='Solução esperada')),
                ('test_cases', models.JSONField(default=list)),
                ('hints', models.JSONField(default=list)),
                ('time_limit_minutes', models.IntegerField(default=30)),
                ('max_points', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Interactive Labs',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_structured', models.BooleanField(default=True, help_text='True=obrigatório, False=trilha')),
                ('duration_minutes', models.IntegerField(default=120)),
                ('learning_objectives', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_paths', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='quizz_app.learningpath')),
            ],
            options={
                'ordering': ['difficulty_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RealWorldScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('scenario_type', models.CharField(choices=[('INCIDENT_RESPONSE', 'Incident Response'), ('MALWARE_ANALYSIS', 'Malware Analysis'), ('LOG_FORENSICS', 'Log Forensics'), ('PENETRATION_TEST_DEFENSE', 'Penetration Test Defense'), ('THREAT_DETECTION', 'Threat Detection'), ('SECURE_CODE_REVIEW', 'Secure Code Review')], max_length=50)),
                ('story', models.TextField(help_text='Contexto narrativo do desafio')),
                ('sample_data', models.JSONField(default=dict)),
                ('expected_findings', models.JSONField(default=list)),
                ('points_max', models.IntegerField(default=200)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Real World Scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PYTHON_BASICS', 'Python Basics'), ('NETWORK_SECURITY', 'Network Security'), ('CRYPTOGRAPHY', 'Cryptography'), ('LOG_ANALYSIS', 'Log Analysis'), ('INCIDENT_RESPONSE', 'Incident Response'), ('WEB_SECURITY', 'Web Security'), ('MALWARE_ANALYSIS', 'Malware Analysis'), ('THREAT_INTEL', 'Threat Intelligence'), ('SECURE_CODING', 'Secure Coding'), ('API_SECURITY', 'API Security')], max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_skills', to='quizz_app.skill')),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('findings', models.JSONField(default=list)),
                ('analysis', models.TextField(help_text='Análise detalhada')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PARTIAL', 'Partially Correct'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('time_taken_minutes', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizz_app.realworldscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='realworldscenario',
            name='skills_covered',
            field=models.ManyToManyField(related_name='scenarios', to='quizz_app.skill'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('CODE_SNIPPET', 'Code Snippet'), ('COMMAND_LINE', 'Command Line'), ('LOG_ANALYSIS', 'Log Analysis'), ('FILL_IN_BLANK', 'Fill in the Blank'), ('TRUE_FALSE', 'True/False')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(help_text='Feedback detalhado')),
                ('code_context', models.TextField(blank=True, help_text='Para code snippets')),
                ('points', models.IntegerField(default=10)),
                ('interleaving_group', models.IntegerField(default=0, help_text='Para misturar tópicos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizz_app.skill')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['interleaving_group', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('INTERACTIVE', 'Interactive'), ('LAB', 'Hands-on Lab'), ('SCENARIO', 'Real-world Scenario'), ('ASSESSMENT', 'Assessment/Quiz')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('content', models.TextField()),
                ('resources', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quizz_app.learningpath')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='quizz_app.skill')),
            ],
            options={
                'ordering': ['learning_path', 'order'],
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='skills',
            field=models.ManyToManyField(related_name='learning_paths', to='quizz_app.skill'),
        ),
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_code', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('test_results', models.JSONField(default=list)),
                ('hints_used', models.IntegerField(default=0)),
                ('time_taken_minutes', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizz_app.interactivelab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='interactivelab',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactive_lab', to='quizz_app.module'),
        ),
        migrations.CreateModel(
            name='AdaptiveQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('questions_asked', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('last_performance', models.FloatField(default=0)),
                ('should_increase_difficulty', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('state', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_quizzes', to='quizz_app.learningpath')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizz_app.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_level', models.FloatField(default=0)),
                ('times_reviewed', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('strength', models.FloatField(default=0)),
                ('weakness', models.FloatField(default=0)),
                ('review_interval', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mastery', to='quizz_app.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_date'], name='quizz_app_u_user_id_42d9ce_idx'), models.Index(fields=['mastery_level'], name='quizz_app_u_mastery_ae7394_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('progress_percentage', models.FloatField(default=0)),
                ('modules_completed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quizz_app.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='quizz_app_u_user_id_1995bf_idx'), models.Index(fields=['completed_at'], name='quizz_app_u_complet_31f355_idx')],
                'unique_together': {('user', 'learning_path')},
            },
        ),
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=0)),
                ('points_next_level', models.IntegerField(default=1000)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('max_streak_days', models.IntegerField(default=0)),
                ('total_achievements', models.IntegerField(default=0)),
                ('total_labs_completed', models.IntegerField(default=0)),
                ('total_scenarios_completed', models.IntegerField(default=0)),
                ('total_skills_mastered', models.IntegerField(default=0)),
                ('rank', models.CharField(choices=[('NOVICE', 'Novice'), ('LEARNER', 'Learner'), ('PRACTITIONER', 'Practitioner'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='NOVICE', max_length=20)),
                ('last_activity_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Gamification',
                'indexes': [models.Index(fields=['level', '-total_points'], name='quizz_app_u_level_231896_idx'), models.Index(fields=['rank'], name='quizz_app_u_rank_258ff8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.FloatField(default=100)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', 'unlocked_at'], name='quizz_app_u_user_id_5419e7_idx')],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'difficulty'], name='quizz_app_s_categor_97073b_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['created_at'], name='quizz_app_s_created_b2e5de_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariosubmission',
            index=models.Index(fields=['user', 'scenario', '-submitted_at'], name='quizz_app_s_user_id_0e955d_idx'),
        ),
        migrations.AddIndex(
            model_name='realworldscenario',
            index=models.Index(fields=['scenario_type', 'difficulty'], name='quizz_app_r_scenari_d19930_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['skill', 'difficulty'], name='quizz_app_q_skill_i_ec2620_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['interleaving_group'], name='quizz_app_q_interle_341459_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['learning_path', 'order'], name='quizz_app_m_learnin_dc911e_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', 'difficulty_level'], name='quizz_app_l_is_publ_756e99_idx'),
        ),
        migrations.AddIndex(
            model_name='labsubmission',
            index=models.Index(fields=['user', 'lab', '-submitted_at'], name='quizz_app_l_user_id_a4505d_idx'),
        ),
        migrations.AddIndex(
            model_name='interactivelab',
            index=models.Index(fields=['difficulty', 'created_at'], name='quizz_app_i_difficu_2b895b_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivequiz',
            index=models.Index(fields=['user', 'status'], name='quizz_app_a_user_id_2b364f_idx'),
        ),
    ]
