# Generated by Django 5.2.17 on 2026-09-01 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('LOGIN', 'Login de usuário'), ('LOGOUT', 'Logout de usuário'), ('REGISTRO', 'Novo registro de usuário'), ('VER_PRODUCTO', 'Visualización de producto'), ('AGREGAR_CARRITO', 'Agregar producto al carrito'), ('ELIMINAR_CARRITO', 'Eliminar producto del carrito'), ('CREAR_PEDIDO', 'Crear pedido'), ('COMPLETAR_PEDIDO', 'Completar pedido'), ('CANCELAR_PEDIDO', 'Cancelar pedido'), ('ACTUALIZAR_PERFIL', 'Actualizar perfil de usuario'), ('CAMBIAR_CONTRASEÑA', 'Cambiar contraseña'), ('RESEÑA_PRODUCTO', 'Crear reseña de producto'), ('BUSCAR', 'Búsqueda en la tienda'), ('FILTRAR', 'Aplicar filtros de búsqueda'), ('OTRO', 'Otro evento')], max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'verbose_name_plural': 'Tipos de eventos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Login de usuário'), ('LOGOUT', 'Logout de usuário'), ('REGISTRO', 'Novo registro de usuário'), ('VER_PRODUCTO', 'Visualización de producto'), ('AGREGAR_CARRITO', 'Agregar producto al carrito'), ('ELIMINAR_CARRITO', 'Eliminar producto del carrito'), ('CREAR_PEDIDO', 'Crear pedido'), ('COMPLETAR_PEDIDO', 'Completar pedido'), ('CANCELAR_PEDIDO', 'Cancelar pedido'), ('ACTUALIZAR_PERFIL', 'Actualizar perfil de usuario'), ('CAMBIAR_CONTRASEÑA', 'Cambiar contraseña'), ('RESEÑA_PRODUCTO', 'Crear reseña de producto'), ('BUSCAR', 'Búsqueda en la tienda'), ('FILTRAR', 'Aplicar filtros de búsqueda'), ('OTRO', 'Otro evento')], default='OTRO', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='eventos_eve_fecha_c_de7615_idx'), models.Index(fields=['usuario', '-fecha_creacion'], name='eventos_eve_usuario_f2f30a_idx'), models.Index(fields=['tipo', '-fecha_creacion'], name='eventos_eve_tipo_433ab3_idx')],
            },
        ),
    ]
